export interface PageTemplateParams {
  id: string;
  title: string;
  components: any[];
  language: 'zh' | 'en';
  styling: 'tailwind' | 'bootstrap' | 'custom';
  navigation: string;
  content: string;
  scripts: string;
}

export const pageTemplate = (params: PageTemplateParams): string => {
  const { id, title, language, styling, navigation, content, scripts } = params;
  
  const styleImports = getStyleImports(styling);
  const scriptImports = getScriptImports(styling);
  
  return `<!DOCTYPE html>
<html lang="${language === 'zh' ? 'zh-CN' : 'en'}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="${title} - Generated by IdeaCanvas">
    <title>${title}</title>
    ${styleImports}
    <link rel="stylesheet" href="styles.css">
    ${styling === 'custom' ? '<link rel="stylesheet" href="components.css">' : ''}
    <style>
        /* Page-specific styles */
        .message {
            position: fixed;
            top: 20px;
            right: 20px;
            padding: 1rem 1.5rem;
            border-radius: 0.25rem;
            font-weight: 500;
            z-index: 1000;
            animation: slideIn 0.3s ease-out;
        }
        
        .message-success {
            background-color: #10b981;
            color: white;
        }
        
        .message-error {
            background-color: #ef4444;
            color: white;
        }
        
        .message-warning {
            background-color: #f59e0b;
            color: white;
        }
        
        .message-info {
            background-color: #3b82f6;
            color: white;
        }
        
        @keyframes slideIn {
            from {
                transform: translateX(100%);
                opacity: 0;
            }
            to {
                transform: translateX(0);
                opacity: 1;
            }
        }
        
        .error {
            border-color: #ef4444 !important;
        }
        
        .page {
            display: none;
        }
        
        .page[data-path="/"] {
            display: block;
        }
    </style>
</head>
<body>
    <div id="app" ${styling === 'tailwind' ? 'class="min-h-screen bg-gray-50"' : ''}>
        ${navigation}
        
        <div class="container">
            <div class="page" data-path="/${title.toLowerCase().replace(/\s+/g, '-')}" data-page-id="${id}">
                ${content}
            </div>
        </div>
    </div>
    
    ${scriptImports}
    <script type="module">
        ${scripts}
    </script>
    <script type="module" src="app.js"></script>
</body>
</html>`;
};

function getStyleImports(styling: string): string {
  switch (styling) {
    case 'tailwind':
      return `
    <!-- Tailwind CSS -->
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">`;
    
    case 'bootstrap':
      return `
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" rel="stylesheet">`;
    
    default:
      return `
    <!-- Custom CSS Framework -->`;
  }
}

function getScriptImports(styling: string): string {
  switch (styling) {
    case 'bootstrap':
      return `
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>`;
    
    default:
      return '';
  }
}

export const indexTemplate = (pages: any[], language: 'zh' | 'en', styling: string): string => {
  const pageLinks = pages.map(page => `
        <li>
            <a href="${page.route}" class="${styling === 'tailwind' ? 'text-blue-600 hover:underline' : 'link'}">${page.name}</a>
        </li>`).join('');

  return `<!DOCTYPE html>
<html lang="${language === 'zh' ? 'zh-CN' : 'en'}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${language === 'zh' ? '应用首页' : 'Application Home'} - Generated by IdeaCanvas</title>
    ${getStyleImports(styling)}
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div id="app" ${styling === 'tailwind' ? 'class="min-h-screen bg-gray-50"' : ''}>
        <div class="container ${styling === 'tailwind' ? 'mx-auto px-4 py-8' : ''}">
            <h1 ${styling === 'tailwind' ? 'class="text-3xl font-bold mb-6"' : ''}>
                ${language === 'zh' ? '欢迎使用生成的应用' : 'Welcome to Generated Application'}
            </h1>
            
            <div ${styling === 'tailwind' ? 'class="bg-white rounded-lg shadow p-6"' : 'class="card"'}>
                <h2 ${styling === 'tailwind' ? 'class="text-xl font-semibold mb-4"' : ''}>
                    ${language === 'zh' ? '可用页面' : 'Available Pages'}
                </h2>
                <ul ${styling === 'tailwind' ? 'class="space-y-2"' : ''}>
                    ${pageLinks}
                </ul>
            </div>
            
            <div ${styling === 'tailwind' ? 'class="mt-8 text-gray-600"' : 'class="footer"'}>
                <p>${language === 'zh' ? '此应用由 IdeaCanvas 自动生成' : 'This application was generated by IdeaCanvas'}</p>
            </div>
        </div>
    </div>
    
    ${getScriptImports(styling)}
    <script type="module" src="app.js"></script>
</body>
</html>`;
};